// lib.rs — Application root: declares all modules and builds the Tauri app
//
// In Rust, `mod module_name;` tells the compiler:
// "There's a file called module_name.rs in this directory — include it."
// This is how Rust knows about all our modules. Without these declarations,
// the compiler won't even look at those files.

// ─── Module declarations ───
//
// Crypto, SVF format I/O, and device fingerprinting now live in the shared
// `svf-core` crate (../../crates/svf-core), which is also consumed by the
// encryptor app and the mobile JNI/FFI shims. That keeps wire-format and
// key-derivation logic bit-for-bit identical across all clients.
pub mod commands;
pub mod errors;
pub mod license;
pub mod player;
pub mod security;
pub mod watermark;

/// Build and run the Tauri application.
///
/// This function is called from main.rs. It:
/// 1. Creates the Tauri app builder
/// 2. Registers plugins (dialog, fs, shell)
/// 3. Registers our IPC command handlers
/// 4. Launches the app window
///
/// #[cfg_attr(mobile, tauri::mobile_entry_point)] is a Tauri macro
/// that makes this work on mobile too (not relevant for us, but good practice).
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let app_state = commands::AppState::new();
    // Clone the playback slot for the custom-protocol handler — same Arc as the
    // managed AppState, so start_playback / stop_playback are visible to the
    // stream handler.
    let playback_slot = app_state.active_playback.clone();

    tauri::Builder::default()
        // ─── Tauri plugins ───
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        // ─── `stream` custom protocol: serves decrypted video ranges over IPC,
        //     with NO TCP socket / port. Fixes QA SP-006/007/010/013 (the old
        //     localhost http://127.0.0.1:<port>/video.mp4?token= URL is gone).
        .register_uri_scheme_protocol("stream", move |_ctx, request| {
            crate::player::serve_stream(&playback_slot, &request)
        })
        // ─── App-wide state (accessible via State<'_, AppState> in commands) ───
        .manage(app_state)
        // ─── IPC command handlers (callable from React via invoke()) ───
        .invoke_handler(tauri::generate_handler![
            commands::get_device_info,
            commands::get_app_version,
            commands::check_auth,
            commands::login,
            commands::login_with_key,
            commands::logout,
            commands::scan_library,
            commands::start_playback,
            commands::stop_playback,
            commands::download_svf,
            commands::report_watch_heartbeat,
        ])
        // ─── App setup (runs once on launch) ───
        .setup(|_app| {
            env_logger::init();
            log::info!("SecurePlayer v{} started", env!("CARGO_PKG_VERSION"));
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// ─── Integration Tests ───
// These tests read actual .svf files generated by the Python encryption tool
// and verify end-to-end decryption works correctly.

#[cfg(test)]
mod integration_tests {
    use svf_core::{decrypt_chunk, SecureKey, SvfFile};
    use sha2::{Digest, Sha256};
    use std::path::PathBuf;

    /// Helper: get path to the test .svf file
    fn test_svf_path() -> PathBuf {
        // Navigate from src-tauri/ up to video-platform/test-videos/encrypted/
        let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        path.push(".."); // up from src-tauri to player/
        path.push(".."); // up from player to video-platform/
        path.push("test-videos");
        path.push("encrypted");
        path.push("11111111-1111-1111-1111-111111111111_720p.svf");
        path
    }

    /// The master key used to encrypt the test files
    fn test_master_key() -> [u8; 32] {
        hex::decode("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
            .unwrap()
            .try_into()
            .unwrap()
    }

    #[test]
    fn test_parse_svf_header() {
        let path = test_svf_path();
        if !path.exists() {
            eprintln!("Skipping: test .svf file not found at {:?}", path);
            return;
        }

        let svf = SvfFile::open(&path).expect("Failed to open .svf file");

        // Verify header fields
        assert_eq!(svf.header.version, 1);
        assert_eq!(svf.header.quality, 1); // 720p
        assert_eq!(svf.header.width, 1280);
        assert_eq!(svf.header.height, 720);
        assert_eq!(svf.header.codec, 0); // H.264
        assert_eq!(svf.header.chunk_size, 1_048_576); // 1 MiB
        assert!(svf.header.chunk_count > 0);
        assert_eq!(svf.header.title, "SAP HANA Module 3: Data Modeling");
        assert_eq!(svf.header.quality_label(), "720p");

        // Verify video_id and tenant_id
        let expected_vid = hex::decode("11111111111111111111111111111111").unwrap();
        let expected_tid = hex::decode("22222222222222222222222222222222").unwrap();
        assert_eq!(svf.header.video_id.as_slice(), expected_vid.as_slice());
        assert_eq!(svf.header.tenant_id.as_slice(), expected_tid.as_slice());

        // Verify chunk index was loaded
        assert_eq!(svf.chunk_index.len(), svf.header.chunk_count as usize);

        println!("Header parsed successfully:");
        println!("  Title: {}", svf.header.title);
        println!("  Quality: {}", svf.header.quality_label());
        println!("  Resolution: {}x{}", svf.header.width, svf.header.height);
        println!("  Duration: {}ms", svf.header.duration_ms);
        println!("  Chunks: {}", svf.header.chunk_count);
    }

    #[test]
    fn test_full_decrypt_and_verify_content_hash() {
        let path = test_svf_path();
        if !path.exists() {
            eprintln!("Skipping: test .svf file not found at {:?}", path);
            return;
        }

        let mut svf = SvfFile::open(&path).expect("Failed to open .svf file");

        // Derive the decryption key using the same parameters
        let key = SecureKey::derive_video_key(
            &test_master_key(),
            &svf.header.encryption_salt,
            &svf.header.video_id,
            &svf.header.tenant_id,
            svf.header.quality,
        )
        .expect("Key derivation failed");

        // Decrypt all chunks and concatenate
        let mut decrypted_data: Vec<u8> = Vec::with_capacity(svf.header.original_size as usize);

        for i in 0..svf.chunk_count() {
            // Read encrypted chunk
            let encrypted = svf.read_chunk(i).expect("Failed to read chunk");

            // Verify chunk hash BEFORE decryption (detect tampering)
            assert!(
                svf.verify_chunk_hash(i, &encrypted),
                "Chunk {} hash verification failed — file may be corrupted!",
                i
            );

            // Decrypt
            let decrypted = decrypt_chunk(&key, &svf.header.encryption_nonce, i as u64, &encrypted)
                .expect("Decryption failed");

            decrypted_data.extend_from_slice(&decrypted);

            println!(
                "  Chunk {}: {} bytes encrypted -> {} bytes decrypted [hash OK]",
                i,
                encrypted.len(),
                decrypted.len()
            );
        }

        // Verify the decrypted content hash matches the original
        let actual_hash = Sha256::digest(&decrypted_data);
        assert_eq!(
            actual_hash.as_slice(),
            svf.header.content_hash.as_slice(),
            "CONTENT HASH MISMATCH!\n\
             The decrypted video data does not match the original.\n\
             Expected: {}\n\
             Got:      {}",
            hex::encode(svf.header.content_hash),
            hex::encode(actual_hash)
        );

        println!("\n=== FULL DECRYPTION VERIFIED ===");
        println!("  Decrypted size: {} bytes ({:.1} MB)",
            decrypted_data.len(),
            decrypted_data.len() as f64 / 1_048_576.0
        );
        println!("  Content SHA-256: {}", hex::encode(actual_hash));
        println!("  Matches original: YES");
    }
}
